name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./registration/pom.xml
          mvn clean package -f ./집행/pom.xml
          mvn clean package -f ./정산/pom.xml
          mvn clean package -f ./budget/pom.xml
          mvn clean package -f ./ParticipationRate/pom.xml
          mvn clean package -f ./연구노트/pom.xml

      - name: Docker Build and push for Registration
        uses: docker/build-push-action@v4
        with:
          context: ./registration
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/registration:latest
            ghcr.io/${{ github.repository }}/registration:${{ github.ref_name }}
            
      - name: Docker Build and push for 집행
        uses: docker/build-push-action@v4
        with:
          context: ./집행
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/집행:latest
            ghcr.io/${{ github.repository }}/집행:${{ github.ref_name }}
            
      - name: Docker Build and push for 정산
        uses: docker/build-push-action@v4
        with:
          context: ./정산
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/정산:latest
            ghcr.io/${{ github.repository }}/정산:${{ github.ref_name }}
            
      - name: Docker Build and push for Budget
        uses: docker/build-push-action@v4
        with:
          context: ./budget
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/budget:latest
            ghcr.io/${{ github.repository }}/budget:${{ github.ref_name }}
            
      - name: Docker Build and push for ParticipationRate
        uses: docker/build-push-action@v4
        with:
          context: ./ParticipationRate
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/participationrate:latest
            ghcr.io/${{ github.repository }}/participationrate:${{ github.ref_name }}
            
      - name: Docker Build and push for 연구노트
        uses: docker/build-push-action@v4
        with:
          context: ./연구노트
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/연구노트:latest
            ghcr.io/${{ github.repository }}/연구노트:${{ github.ref_name }}
            
