server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: registration
          uri: http://localhost:8082
          predicates:
            - Path=/undefined/**, /projectMasters/**, 
        - id: 집행
          uri: http://localhost:0
          predicates:
            - Path=/expenseResolutions/**, 
        - id: 정산
          uri: http://localhost:0
          predicates:
            - Path=/projects/**, /expenseTables/**, 
        - id: budget
          uri: http://localhost:0
          predicates:
            - Path=/undefined/**, /budgets/**, 
        - id: ParticipationRate
          uri: http://localhost:0
          predicates:
            - Path=/undefined/**, /researchers/**, 
        - id: 연구노트
          uri: http://localhost:0
          predicates:
            - Path=/researchNotes/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: registration
          uri: http://registration:8080
          predicates:
            - Path=/undefined/**, /projectMasters/**, 
        - id: 집행
          uri: http://집행:8080
          predicates:
            - Path=/expenseResolutions/**, 
        - id: 정산
          uri: http://정산:8080
          predicates:
            - Path=/projects/**, /expenseTables/**, 
        - id: budget
          uri: http://budget:8080
          predicates:
            - Path=/undefined/**, /budgets/**, 
        - id: ParticipationRate
          uri: http://participationRate:8080
          predicates:
            - Path=/undefined/**, /researchers/**, 
        - id: 연구노트
          uri: http://연구노트:8080
          predicates:
            - Path=/researchNotes/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
