Feature: ProjectMaster
    Scenario Outline: Whenever BudgetCreated, ProjectUpdated
        Given BudgetCreated ( "<BudgetCreated_taskManagementNumber>" "<BudgetCreated_governmentSupportAmount>" "<BudgetCreated_privateRatio>" "<BudgetCreated_privateCashRatio>" "<BudgetCreated_laborCost>" "<BudgetCreated_internalLaborCost>" "<BudgetCreated_externalLaborCost>" "<BudgetCreated_studentResearchCost>" "<BudgetCreated_materialCost>" "<BudgetCreated_researchFacilityCost>" "<BudgetCreated_activityCost>" "<BudgetCreated_indirectCost>" ) is published and  ( "<ProjectMaster_projectId>" "<ProjectMaster_noticeProjectName>" "<ProjectMaster_projectManager>" "<ProjectMaster_projectName>" "<ProjectMaster_rfpName>" "<ProjectMaster_researchManager>" "<ProjectMaster_cashBurden>" "<ProjectMaster_materialBurden>" "<ProjectMaster_totalProjectCost>" "<ProjectMaster_currentYearProjectCost>" "<ProjectMaster_totalProjectDuration>" "<ProjectMaster_currentYearDuration>" "<ProjectMaster_organName>" "<ProjectMaster_organBusinessNumber>" "<ProjectMaster_organDirector>" "<ProjectMaster_receiptDate>" "<ProjectMaster_selectionNotification>" "<ProjectMaster_accountAllocation>" "<ProjectMaster_projectPlanFile>" "<ProjectMaster_participationType>" ) is present
        When update master
        Then ProjectUpdated ( "<ProjectUpdated_noticeProjectName>" ) should publish

        Examples:
            |	ProjectMaster_projectId	|	ProjectMaster_noticeProjectName	|	ProjectMaster_projectManager	|	ProjectMaster_projectName	|	ProjectMaster_rfpName	|	ProjectMaster_researchManager	|	ProjectMaster_cashBurden	|	ProjectMaster_materialBurden	|	ProjectMaster_totalProjectCost	|	ProjectMaster_currentYearProjectCost	|	ProjectMaster_totalProjectDuration	|	ProjectMaster_currentYearDuration	|	ProjectMaster_organName	|	ProjectMaster_organBusinessNumber	|	ProjectMaster_organDirector	|	ProjectMaster_receiptDate	|	ProjectMaster_selectionNotification	|	ProjectMaster_accountAllocation	|	ProjectMaster_projectPlanFile	|	ProjectMaster_participationType	|	BudgetCreated_taskManagementNumber	|	BudgetCreated_governmentSupportAmount	|	BudgetCreated_privateRatio	|	BudgetCreated_privateCashRatio	|	BudgetCreated_laborCost	|	BudgetCreated_internalLaborCost	|	BudgetCreated_externalLaborCost	|	BudgetCreated_studentResearchCost	|	BudgetCreated_materialCost	|	BudgetCreated_researchFacilityCost	|	BudgetCreated_activityCost	|	BudgetCreated_indirectCost	|	ProjectUpdated_noticeProjectName	|
            |      |      |      |      |      |      |      |      |      |      |      |      |      |      |      |      |      |      |      |      |   |   |   |   |   |   |   |   |   |   |   |   |    |


