---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration
  labels:
    app: registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
        - name: registration
          image: username/registration:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 집행
  labels:
    app: 집행
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 집행
  template:
    metadata:
      labels:
        app: 집행
    spec:
      containers:
        - name: 집행
          image: username/집행:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 정산
  labels:
    app: 정산
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 정산
  template:
    metadata:
      labels:
        app: 정산
    spec:
      containers:
        - name: 정산
          image: username/정산:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget
  labels:
    app: budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget
  template:
    metadata:
      labels:
        app: budget
    spec:
      containers:
        - name: budget
          image: username/budget:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ParticipationRate
  labels:
    app: ParticipationRate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ParticipationRate
  template:
    metadata:
      labels:
        app: ParticipationRate
    spec:
      containers:
        - name: ParticipationRate
          image: username/ParticipationRate:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 연구노트
  labels:
    app: 연구노트
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 연구노트
  template:
    metadata:
      labels:
        app: 연구노트
    spec:
      containers:
        - name: 연구노트
          image: username/연구노트:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: registration
  labels:
    app: registration
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: registration


---


apiVersion: v1
kind: Service
metadata:
  name: 집행
  labels:
    app: 집행
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 집행


---


apiVersion: v1
kind: Service
metadata:
  name: 정산
  labels:
    app: 정산
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 정산


---


apiVersion: v1
kind: Service
metadata:
  name: budget
  labels:
    app: budget
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: budget


---


apiVersion: v1
kind: Service
metadata:
  name: ParticipationRate
  labels:
    app: ParticipationRate
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ParticipationRate


---


apiVersion: v1
kind: Service
metadata:
  name: 연구노트
  labels:
    app: 연구노트
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: 연구노트

